[tool.ruff]
# Target Python 3.12
target-version = "py312"
# Same as Black
line-length = 88

[tool.ruff.lint]
# Enable pycodestyle ('E'), pyflakes ('F'), and isort ('I') codes
select = ["E", "F", "I", "N", "B", "Q", "RUF", "PL", "UP"]
ignore = []

[tool.ruff.lint.mccabe]
# Flag errors if the complexity exceeds 10
max-complexity = 10

[tool.ruff.lint.isort]
known-first-party = ["rankor", "player_tracker"]

[tool.mypy]
python_version = "3.12"
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "rankor.settings"