# Generated by Django 5.1.4 on 2024-12-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SummonerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discord_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("summoner_name", models.CharField(db_index=True, max_length=100)),
                ("puuid", models.CharField(db_index=True, max_length=10)),
                (
                    "server_region",
                    models.CharField(
                        choices=[
                            ("EUW1", "Europe West"),
                            ("NA1", "North America"),
                            ("KR", "Korea"),
                        ],
                        default="EUW1",
                        max_length=5,
                    ),
                ),
                (
                    "current_solo_rank",
                    models.CharField(
                        choices=[
                            ("IRON", "Iron"),
                            ("BRONZE", "Bronze"),
                            ("SILVER", "Silver"),
                            ("GOLD", "Gold"),
                            ("PLATINUM", "Platinum"),
                            ("EMERALD", "Emerald"),
                            ("DIAMOND", "Diamond"),
                            ("MASTER", "Master"),
                            ("GRANDMASTER", "Grandmaster"),
                            ("CHALLENGER", "Challenger"),
                            ("UNRANKED", "Unranked"),
                        ],
                        default="UNRANKED",
                        max_length=20,
                    ),
                ),
                (
                    "current_solo_division",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("I", "I"),
                            ("II", "II"),
                            ("III", "III"),
                            ("IV", "IV"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "current_flex_rank",
                    models.CharField(
                        choices=[
                            ("IRON", "Iron"),
                            ("BRONZE", "Bronze"),
                            ("SILVER", "Silver"),
                            ("GOLD", "Gold"),
                            ("PLATINUM", "Platinum"),
                            ("EMERALD", "Emerald"),
                            ("DIAMOND", "Diamond"),
                            ("MASTER", "Master"),
                            ("GRANDMASTER", "Grandmaster"),
                            ("CHALLENGER", "Challenger"),
                            ("UNRANKED", "Unranked"),
                        ],
                        default="UNRANKED",
                        max_length=20,
                    ),
                ),
                (
                    "current_flex_division",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("I", "I"),
                            ("II", "II"),
                            ("III", "III"),
                            ("IV", "IV"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("current_solo_lp", models.IntegerField(default=0)),
                ("last_check_timestamp", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Summoner Profile",
                "verbose_name_plural": "Summoner Profiles",
            },
        ),
    ]
