# Generated by Django 5.1.4 on 2024-12-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="summonerprofile",
            name="current_flex_lp",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="summonerprofile",
            name="highest_achieved_rank_flex",
            field=models.CharField(
                choices=[
                    ("IRON", "Iron"),
                    ("BRONZE", "Bronze"),
                    ("SILVER", "Silver"),
                    ("GOLD", "Gold"),
                    ("PLATINUM", "Platinum"),
                    ("EMERALD", "Emerald"),
                    ("DIAMOND", "Diamond"),
                    ("MASTER", "Master"),
                    ("GRANDMASTER", "Grandmaster"),
                    ("CHALLENGER", "Challenger"),
                    ("UNRANKED", "Unranked"),
                ],
                default="UNRANKED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="summonerprofile",
            name="highest_achieved_rank_solo",
            field=models.CharField(
                choices=[
                    ("IRON", "Iron"),
                    ("BRONZE", "Bronze"),
                    ("SILVER", "Silver"),
                    ("GOLD", "Gold"),
                    ("PLATINUM", "Platinum"),
                    ("EMERALD", "Emerald"),
                    ("DIAMOND", "Diamond"),
                    ("MASTER", "Master"),
                    ("GRANDMASTER", "Grandmaster"),
                    ("CHALLENGER", "Challenger"),
                    ("UNRANKED", "Unranked"),
                ],
                default="UNRANKED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="summonerprofile",
            name="puuid",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
