# Generated by Django 5.1.4 on 2024-12-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_tracker", "0002_summonerprofile_current_flex_lp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="summonerprofile",
            name="flex_league_id",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="summonerprofile",
            name="flex_losses",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="summonerprofile",
            name="flex_wins",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="summonerprofile",
            name="solo_league_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="summonerprofile",
            name="solo_losses",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="summonerprofile",
            name="solo_wins",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="summonerprofile",
            name="summoner_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="summonerprofile",
            name="tagline",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
